//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTournaments
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDetail
    {
        public short EventDetailID { get; set; }
        public long FK_EventID { get; set; }
        public short FK_EventDetailStatusID { get; set; }
        public string EventDetailName { get; set; }
        public short EventDetailNumber { get; set; }
        public decimal EventDetailOdd { get; set; }
        public Nullable<short> FinishingPostion { get; set; }
        public bool FirstTimer { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual EventDetailStatu EventDetailStatu { get; set; }
    }
}
